name: Check Audiobooks Daily

on:
  schedule:
    - cron: '0 8 * * *'  # Каждый день в 08:00 UTC (11:00 Мск)
  workflow_dispatch:  # Разрешить ручной запуск

jobs:
  check-books:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # Важно: загружаем всю историю чтобы получить series.json
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests beautifulsoup4 python-dotenv

    - name: Show series data
      run: |
        echo "Current series.json content:"
        cat series.json
        echo ""
        echo "Number of series to check:"
        python -c "import json; data = json.load(open('series.json')); print(len(data))"

    - name: Run book checker
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python book_checker.py

    - name: Upload updated series data
      uses: actions/upload-artifact@v4
      with:
        name: series-data
        path: series.json

    - name: Commit and push updates
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
        # Проверяем есть ли изменения в series.json
        if git diff --name-only --exit-code series.json; then
          echo "No changes in series.json"
        else
          echo "Changes detected in series.json, committing..."
          git add series.json
          git commit -m "📚 Auto-update: Updated book series data"
          git push
        fi